jeecloud.exception.service.alreadyExists=Dienst mit dem Namen {0} und URL {1} ist bereits vorhanden
jeecloud.exception.service.notExistsByName=Service mit dem Namen {0} existiert nicht
jeecloud.exception.service.notExistsByNameAndUrl=Service mit dem Namen {0} und {1} url existiert nicht